import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'kz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.whyUs': 'Why Us',
    'nav.cases': 'Cases',
    'nav.pricing': 'Pricing',
    'nav.blog': 'Blog',
    'nav.about': 'About Us',
    'nav.contacts': 'Contacts',
    'nav.discuss': 'Discuss Project',
    'nav.back': 'Back',

    // Hero Section
    'hero.badge': 'IT Solutions for Business',
    'hero.title1': 'We Create',
    'hero.title2': 'Digital Products',
    'hero.titleMobile': 'Custom websites of any complexity in Kazakhstan',
    'hero.titleMobile.before': 'Custom websites of any complexity in',
    'hero.titleMobile.highlight': 'Kazakhstan',
    'hero.title3': 'That Drive Business',
    'hero.description': 'Website development, mobile apps, chatbots, AI solutions, and targeted advertising. We turn ideas into working products.',
    'hero.cta1': 'Start Project',
    'hero.cta2': 'Our Cases',
    'hero.stats.projects': 'Projects',
    'hero.stats.clients': 'Happy Clients',
    'hero.stats.years': 'Years Experience',

    // Services Section
    'services.badge': 'Services',
    'services.title': 'What We',
    'services.titleHighlight': 'Create',
    'services.description': 'Full cycle of digital product development — from idea to launch and support.',
    'services.shatterHint': 'Shake the cards to crack them — one of them hides a coupon',
    'services.productToastTitle': 'New legal assistant demo',
    'services.productToastDescription': 'Test the product: answers on major laws (KoAP and more)',
    'services.coupon.congrats': 'You won',
    'services.coupon.discountLabel': 'discount',
    'services.coupon.codeLabel': 'Coupon code',
    'services.coupon.cta': 'Contact us',
    'services.coupon.targetWeb': 'on website development',
    'services.coupon.targetAll': 'on all services',
    'services.coupon.emptyTitle': 'Empty',
    'services.coupon.emptySubtitle': 'try another card',
    'services.coupon.waMessage':
      "Hello! I won coupon №{code} ({discount} {target}) on the SnowTech website. I'd like to discuss a project.",
    'services.web.title': 'Custom websites of any complexity in Kazakhstan',
    'services.web.description': 'Landing pages, corporate sites, online stores, complex web platforms. Modern technologies and responsive design.',
    'services.mobile.title': 'Mobile Apps',
    'services.mobile.description': 'Native and cross-platform apps for iOS and Android. From MVP to enterprise solutions.',
    'services.chatbot.title': 'Chatbots',
    'services.chatbot.description': 'Intelligent bots for WhatsApp, Telegram, and websites. Automation of customer communication.',
    'services.rag.title': 'RAG Chatbots',
    'services.rag.description': 'AI bots with knowledge base. Answers based on your documents and data.',
    'services.ml.title': 'Machine Learning',
    'services.ml.description': 'Predictive analytics, recommendations, process automation using AI.',
    'services.cv.title': 'Computer Vision',
    'services.cv.description': 'Image and video recognition, object detection, quality control systems.',
    'services.ads.title': 'Targeted Advertising',
    'services.ads.description': 'Effective advertising campaigns on Instagram, TikTok, Facebook. Precise audience targeting and ROI optimization.',
    'services.learnMore': 'Learn More',

    // Why Us Section
    'whyUs.badge': 'Advantages',
    'whyUs.title': 'Why',
    'whyUs.titleHighlight': 'Choose Us',
    'whyUs.description': 'We combine deep tech expertise with understanding of business tasks.',
    'whyUs.expertise.title': 'Deep Expertise',
    'whyUs.expertise.description': 'A team of specialists with experience in large projects. We know how to solve complex problems.',
    'whyUs.approach.title': 'Individual Approach',
    'whyUs.approach.description': 'We dive deep into each client\'s specifics. No template solutions.',
    'whyUs.deadlines.title': 'On-time Delivery',
    'whyUs.deadlines.description': 'Transparent development process and timely delivery. You always know what\'s happening.',
    'whyUs.support.title': 'Support & Development',
    'whyUs.support.description': 'We don\'t abandon projects. Technical support and continuous improvement.',
    'whyUs.tech.title': 'Technology Stack',
    'whyUs.tech.description': 'We use modern technologies for reliable and scalable solutions.',

    // Cases Section
    'cases.badge': 'Cases',
    'cases.title': 'Projects We\'re',
    'cases.titleHighlight': 'Proud Of',
    'cases.description': 'Real results for real businesses. See how we solve client challenges.',
    'cases.viewAll': 'View All Projects',
    'cases.ecommerce.title': 'E-commerce Platform',
    'cases.ecommerce.client': 'Retail Chain',
    'cases.ecommerce.description': 'Scalable online store with ML recommendations.',
    'cases.ecommerce.result1': '+180% conversion',
    'cases.ecommerce.result2': '3 months',
    'cases.ecommerce.result3': '50K+ users',
    'cases.carRental.title': 'Car Rental Platform',
    'cases.carRental.client': 'Car Rental Company',
    'cases.carRental.description': 'Online platform for car rental with booking system.',
    'cases.carRental.result1': '+120% bookings',
    'cases.carRental.result2': '2 months',
    'cases.carRental.result3': '500+ cars',
    'cases.realEstate.title': 'Real Estate Website',
    'cases.realEstate.client': 'Real Estate Agency',
    'cases.realEstate.description': 'Website for real estate agency with property listings.',
    'cases.realEstate.result1': '+200% inquiries',
    'cases.realEstate.result2': '3 months',
    'cases.realEstate.result3': '1000+ properties',
    'cases.transport.title': 'Transport Management',
    'cases.transport.client': 'Logistics Company',
    'cases.transport.description': 'Fleet management system with real-time tracking.',
    'cases.transport.result1': '+40% efficiency',
    'cases.transport.result2': '3 months',
    'cases.transport.result3': '500+ vehicles',
    'cases.automation.title': 'Process Automation',
    'cases.automation.client': 'Production',
    'cases.automation.description': 'Automated workflow system for manufacturing processes.',
    'cases.automation.result1': '-60% manual work',
    'cases.automation.result2': '5 months',
    'cases.automation.result3': '24/7 operation',
    'cases.tron.title': 'Telegram Mini App Tron',
    'cases.tron.client': 'Gaming Platform',
    'cases.tron.description': 'Interactive game mini app for Telegram with engaging gameplay.',
    'cases.tron.result1': '+300% engagement',
    'cases.tron.result2': '1.5 months',
    'cases.tron.result3': '50K+ players',
    'cases.calculator.title': 'Telegram Mini App',
    'cases.calculator.client': 'Gaming Platform',
    'cases.calculator.description': 'Interactive game mini app for Telegram with engaging gameplay.',

    // Case Modal UI
    'casemodal.projectDescription': 'Project Description',
    'casemodal.techStack': 'Tech Stack',
    'casemodal.results': 'Key Results',
    'casemodal.viewLive': 'Live',
    'casemodal.close': 'Close',

    // Real cases
    'cases.supratrade.title': 'Supratrade — trading platform',
    'cases.supratrade.client': 'Supratrade',
    'cases.supratrade.description': 'A modern B2B trading platform with a product catalog, client area and a tailored CMS.',
    'cases.supratrade.long': 'Supratrade is a B2B trading platform we built from the ground up as a custom solution. The site unifies the product catalog, the ordering workflow and the client area into a single experience, letting the Supratrade team onboard new partners and manage deals faster.\n\nThe frontend was built with React + TypeScript with a modular architecture focused on speed and clean UX. The backend on Node.js handles authentication, the catalog and order processing, while PostgreSQL stores products, clients and transactions reliably. We put a lot of effort into content management so the team can update the catalog without any developer involvement.',
    'cases.supratrade.result1': '+150% qualified leads',
    'cases.supratrade.result2': '3 months to launch',
    'cases.supratrade.result3': '200+ B2B partners',

    'cases.autoRent.title': 'AutoRent — car rental service',
    'cases.autoRent.client': 'Car rental company',
    'cases.autoRent.description': 'An online car rental platform with booking, payment and a driver dashboard.',
    'cases.autoRent.long': 'AutoRent is a full-featured car rental platform with a booking flow, online payments and a client dashboard. We designed the UX around speed: users can filter cars, pick dates, check the price instantly and pay online in just a couple of clicks.\n\nThe frontend is built with React and Framer Motion for smooth transitions. Node.js powers the API, MongoDB stores the fleet, bookings and users, and Stripe handles payments. The admin area lets the operator add cars, manage tariffs, track bookings in real time and work with clients.',
    'cases.autoRent.result1': '+120% online bookings',
    'cases.autoRent.result2': '2 months to launch',
    'cases.autoRent.result3': '500+ cars in fleet',

    'cases.mosSeptik.title': 'Mos-Septik — septic tanks & installation',
    'cases.mosSeptik.client': 'Mos-Septik',
    'cases.mosSeptik.description': 'SEO-ready landing for a septic tank sales & installation company.',
    'cases.mosSeptik.long': 'Mos-Septik is a niche landing site for a septic tank sales and installation company. The main goal was to capture leads and rank well in search: we built an SEO-oriented structure with a clear product catalog, calculator, request forms and trust blocks (cases, reviews, certificates).\n\nWe built the site on React + Next.js so the pages are server-rendered and indexed well. Tailwind makes the design consistent and responsive on any device. Forms are connected to a CRM so every request lands in the manager\'s inbox instantly.',
    'cases.mosSeptik.result1': 'Top-10 in organic search',
    'cases.mosSeptik.result2': '1.5 months to launch',
    'cases.mosSeptik.result3': '+210% leads',

    'cases.blueberry.title': 'Blueberry — berry farm store',
    'cases.blueberry.client': 'Blueberry Farm',
    'cases.blueberry.description': 'An online store for a berry farm with delivery, payments and a Telegram bot.',
    'cases.blueberry.long': 'Blueberry is an online store for a berry farm: a bright, seasonal product catalog, order flow, online payments and delivery integration. Alongside the store we built a Telegram bot that reminds regular customers about new harvests and confirms orders.\n\nThe frontend on React delivers a rich, interactive shopping experience. Node.js and PostgreSQL power the catalog, orders and client base, while Stripe covers payments. The bot is integrated with the same backend so orders from the website and from Telegram live in one system.',
    'cases.blueberry.result1': '+180% online orders',
    'cases.blueberry.result2': '2 months to launch',
    'cases.blueberry.result3': '30K+ monthly visits',

    'cases.airGun.title': 'AirGun — pneumatic weapons store',
    'cases.airGun.client': 'AirGun Shop',
    'cases.airGun.description': 'An e-commerce store for pneumatic weapons and accessories.',
    'cases.airGun.long': 'AirGun is a niche e-commerce store for pneumatic weapons, optics and accessories. We focused on a strong product page: detailed specs, multiple photos, reviews, related items and fast "buy in one click".\n\nThe stack is React + TypeScript on the client and Node.js + PostgreSQL on the server. Online payments are integrated for instant checkout, and the admin is connected to the manager\'s CRM so order handling stays within a single workflow.',
    'cases.airGun.result1': '+140% sales conversion',
    'cases.airGun.result2': '2.5 months to launch',
    'cases.airGun.result3': '1500+ SKUs',

    'cases.zapImport.title': 'ZapImport — spare parts import',
    'cases.zapImport.client': 'ZapImport',
    'cases.zapImport.description': 'A portal for auto spare parts import with catalog parsing and a REST API.',
    'cases.zapImport.long': 'ZapImport is a B2B portal for importing auto spare parts. The system aggregates catalogs from several suppliers, normalises the data and exposes a unified search by VIN and article number for partners. The hardest part was building a reliable parsing pipeline with up-to-date prices and stock levels.\n\nThe frontend is built with React. The backend on Node.js with PostgreSQL handles parsing, caching and the REST API, so partners can connect either through the site or directly via API.',
    'cases.zapImport.result1': '+300% order volume',
    'cases.zapImport.result2': '4 months to launch',
    'cases.zapImport.result3': '50+ B2B clients',

    // Testimonials Section
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'What Our',
    'testimonials.titleHighlight': 'Clients Say',
    'testimonials.description': 'Real feedback from the businesses we have helped to grow digitally.',
    'testimonials.prev': 'Previous testimonial',
    'testimonials.next': 'Next testimonial',
    'testimonials.t1': 'SnowTech built our e-commerce platform from scratch. Conversion grew by 180% in the first quarter — an excellent result and very smooth communication along the way.',
    'testimonials.t2': 'A sharp team — they picked up our TikTok and Instagram ads and cut CPA in half in a month. Reports are clear, dashboards are transparent.',
    'testimonials.t3': 'They delivered a complex real-estate site with advanced filters ahead of schedule. Support after launch has been top-notch.',
    'testimonials.t4': 'Our fleet management system finally works in real time. The drivers, the ops team and the board — everyone sees the same picture now.',
    'testimonials.t5': 'The automation layer they built shaved 60% off our manual workflow. ROI paid back within 4 months. Highly recommend.',
    'testimonials.t6': 'Our Telegram Mini App hit 50K players in the first two weeks. Gameplay feels native, UX is addictive, performance is flawless.',

    // Contact Section
    'contact.badge': 'Contacts',
    'contact.title': 'Let\'s Discuss Your',
    'contact.titleHighlight': 'Project',
    'contact.description': 'Leave a request and we\'ll contact you within 24 hours to discuss details.',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.message': 'Tell us about your project',
    'contact.form.submit': 'Send Request',
    'contact.form.success': 'Request sent!',
    'contact.form.successDesc': 'We\'ll contact you shortly.',
    'contact.messenger': 'Or write via messenger:',

    // Footer
    'footer.description': 'Developing digital products that drive business. From websites to AI solutions.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.subscribe': 'Subscribe to Updates',
    'footer.subscribeBtn': 'Subscribe',
    'footer.rights': 'All rights reserved.',

    // Pricing Page
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Transparent pricing for all services. Choose your tier or order a custom calculation.',
    'pricing.badge': 'Transparent pricing',
    'pricing.from': 'from',
    'pricing.websites': 'Websites',
    'pricing.additional': 'Additional Services',
    'pricing.landing': 'Landing Page',
    'pricing.landingDesc': 'One-page site for advertising campaigns',
    'pricing.corporate': 'Corporate Site',
    'pricing.corporateDesc': 'Multi-page site with admin panel',
    'pricing.store': 'Online Store',
    'pricing.storeDesc': 'Full e-commerce with payment integration',
    'pricing.platform': 'Web Platform',
    'pricing.platformDesc': 'Complex system with custom logic',
    'pricing.mobile': 'Mobile App',
    'pricing.mobileDesc': 'iOS/Android app',
    'pricing.chatbot': 'Chatbot',
    'pricing.chatbotDesc': 'Bot for messengers',
    'pricing.ragbot': 'RAG Chatbot',
    'pricing.ragbotDesc': 'AI bot with knowledge base',
    'pricing.ml': 'ML Solution',
    'pricing.mlDesc': 'Custom ML model',
    'pricing.cv': 'Computer Vision',
    'pricing.cvDesc': 'Video/image recognition',
    'pricing.instagram': 'Instagram Targeting',
    'pricing.instagramDesc': 'Advertising setup + management',
    'pricing.tiktok': 'TikTok Ads',
    'pricing.tiktokDesc': 'Ad campaign setup',
    'pricing.support': 'Monthly Support',
    'pricing.supportDesc': 'Technical support and updates',
    'pricing.order': 'Order',
    'pricing.custom': 'Custom Calculation',
    'pricing.customDesc': 'Need something special? We\'ll calculate individual cost for your project.',
    'pricing.customBtn': 'Get Calculation',
    'pricing.flipHint': 'Hover or tap — final price is set personally',
    'pricing.discussCta': 'Discuss',

    // Blog Page
    'blog.title': 'Blog',
    'blog.subtitle': 'Useful articles about marketing, advertising, and business promotion in Kazakhstan.',
    'blog.readMore': 'Read More',
    'blog.categories': 'Categories',
    'blog.all': 'All',
    'blog.seo': 'SEO',
    'blog.smm': 'SMM',
    'blog.advertising': 'Advertising',
    'blog.automation': 'Automation',

    // Cases Page
    'casesPage.title': 'Our Projects',
    'casesPage.subtitle': 'Real cases with measurable results. See how we help businesses grow.',
    'casesPage.empty': 'Cases will be added soon',
    'casesPage.emptyDesc': 'We are preparing detailed descriptions of our projects. Stay tuned!',

    // About Page
    'about.badge': 'About Us',
    'about.title': 'About SnowTEch',
    'about.subtitle': 'We are a team of IT professionals creating digital products that drive business growth in Kazakhstan.',
    'about.demo.title': 'Interactive Components',
    'about.demo.rotate': 'Rotating',
    'about.demo.hover': 'Hover Effect',
    'about.demo.color': 'Color Change',
    'about.values.title': 'Our Values',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'We use cutting-edge technologies to create modern solutions.',
    'about.values.team.title': 'Team',
    'about.values.team.description': 'Experienced professionals working together to achieve your goals.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.description': 'We deliver high-quality products that meet your expectations.',
    'about.values.passion.title': 'Passion',
    'about.values.passion.description': 'We love what we do and it shows in our work.',
    'about.cta.title': 'Ready to work with us?',
    'about.cta.description': 'Let\'s discuss your project and create something amazing together.',
    'about.cta.button': 'Get in Touch',

    // Employee Pages
    'employee.iliyas.firstName': 'ILYAS',
    'employee.iliyas.lastName': 'KELES',
    'employee.iliyas.role': 'FULL STACK DEVELOPER',
    'employee.iliyas.experience': 'YEARS OF EXPERIENCE',
    'employee.iliyas.technologies': 'TECHNOLOGIES',
    'employee.iliyas.techStack': 'TECH STACK',
    'employee.iliyas.quote': '"With great power comes great responsibility"',
    'employee.iliyas.quoteAuthor': '- PETER PARKER',
    'employee.iliyas.nextEmployee': 'Next SnowTEch Employee',
    'employee.nurtore.firstName': 'NURTORE',
    'employee.nurtore.lastName': 'Kelesov',
    'employee.nurtore.role': 'BACKEND DEVELOPER',
    'employee.nurtore.roleMobile': 'MOBILE DEVELOPER',
    'employee.nurtore.experience': 'YEARS OF EXPERIENCE',
    'employee.nurtore.technologies': 'TECHNOLOGIES',
    'employee.nurtore.techStack': 'TECH STACK',
    'employee.nurtore.quote': '"I create technologies that change the world"',
    'employee.nurtore.quoteAuthor': '- TONY STARK',
    'employee.nurtore.previousEmployee': 'Previous SnowTEch Employee',
  },
  ru: {
    // Navigation
    'nav.services': 'Услуги',
    'nav.whyUs': 'Почему мы',
    'nav.cases': 'Кейсы',
    'nav.pricing': 'Цены',
    'nav.blog': 'Блог',
    'nav.about': 'О нас',
    'nav.contacts': 'Контакты',
    'nav.discuss': 'Обсудить проект',
    'nav.back': 'Назад',

    // Hero Section
    'hero.badge': 'IT-решения для бизнеса',
    'hero.title1': 'Создаём',
    'hero.title2': 'Цифровые продукты',
    'hero.titleMobile': 'Создание любой сложности сайтов в Казахстане',
    'hero.titleMobile.before': 'Создание любой сложности сайтов в',
    'hero.titleMobile.highlight': 'Казахстане',
    'hero.title3': 'Которые двигают бизнес',
    'hero.description': 'Разработка сайтов, мобильных приложений, чат-ботов, AI-решений и таргетированной рекламы. Превращаем идеи в работающие продукты.',
    'hero.cta1': 'Начать проект',
    'hero.cta2': 'Наши кейсы',
    'hero.stats.projects': 'Проектов',
    'hero.stats.clients': 'Довольных клиентов',
    'hero.stats.years': 'Лет опыта',

    // Services Section
    'services.badge': 'Услуги',
    'services.title': 'Что мы',
    'services.titleHighlight': 'создаём',
    'services.description': 'Полный цикл разработки цифровых продуктов — от идеи до запуска и поддержки.',
    'services.shatterHint': 'Потрясите карточки — одна из них прячет купон со скидкой',
    'services.productToastTitle': 'Новое демо юридического ассистента',
    'services.productToastDescription': 'Протестируйте продукт: отвечает по основным законам (КоАП и др.)',
    'services.coupon.congrats': 'Поздравляем',
    'services.coupon.discountLabel': 'скидка',
    'services.coupon.codeLabel': 'Код купона',
    'services.coupon.cta': 'Связаться',
    'services.coupon.targetWeb': 'на разработку сайтов',
    'services.coupon.targetAll': 'на все услуги',
    'services.coupon.emptyTitle': 'Пусто',
    'services.coupon.emptySubtitle': 'попробуйте другую карточку',
    'services.coupon.waMessage':
      'Здравствуйте! Я выиграл купон №{code} ({discount} {target}) на сайте SnowTech. Хочу обсудить проект.',
    'services.web.title': 'Создание любой сложности сайтов в Казахстане',
    'services.web.description': 'Лендинги, корпоративные сайты, интернет-магазины, сложные веб-платформы. Современные технологии и адаптивный дизайн.',
    'services.mobile.title': 'Мобильные приложения',
    'services.mobile.description': 'Нативные и кроссплатформенные приложения для iOS и Android. От MVP до enterprise решений.',
    'services.chatbot.title': 'Чат-боты',
    'services.chatbot.description': 'Умные боты для WhatsApp, Telegram и веб-сайтов. Автоматизация коммуникации с клиентами.',
    'services.rag.title': 'RAG-чат-боты',
    'services.rag.description': 'AI-боты с базой знаний. Ответы на основе ваших документов и данных.',
    'services.ml.title': 'Machine Learning',
    'services.ml.description': 'Предиктивная аналитика, рекомендательные системы, автоматизация процессов с помощью AI.',
    'services.cv.title': 'Computer Vision',
    'services.cv.description': 'Распознавание изображений и видео, детекция объектов, системы контроля качества.',
    'services.ads.title': 'Таргетированная реклама',
    'services.ads.description': 'Эффективные рекламные кампании в Instagram, TikTok, Facebook. Точный таргетинг и оптимизация ROI.',
    'services.learnMore': 'Подробнее',

    // Why Us Section
    'whyUs.badge': 'Преимущества',
    'whyUs.title': 'Почему',
    'whyUs.titleHighlight': 'выбирают нас',
    'whyUs.description': 'Мы объединяем глубокую техническую экспертизу с пониманием бизнес-задач.',
    'whyUs.expertise.title': 'Глубокая экспертиза',
    'whyUs.expertise.description': 'Команда специалистов с опытом в крупных проектах. Знаем, как решать сложные задачи.',
    'whyUs.approach.title': 'Индивидуальный подход',
    'whyUs.approach.description': 'Погружаемся в специфику каждого клиента. Никаких шаблонных решений.',
    'whyUs.deadlines.title': 'Соблюдение сроков',
    'whyUs.deadlines.description': 'Прозрачный процесс разработки и своевременная сдача. Вы всегда знаете, что происходит.',
    'whyUs.support.title': 'Поддержка и развитие',
    'whyUs.support.description': 'Не бросаем проекты. Техническая поддержка и постоянное улучшение.',
    'whyUs.tech.title': 'Технологический стек',
    'whyUs.tech.description': 'Используем современные технологии для надёжных и масштабируемых решений.',

    // Cases Section
    'cases.badge': 'Кейсы',
    'cases.title': 'Проекты, которыми мы',
    'cases.titleHighlight': 'гордимся',
    'cases.description': 'Реальные результаты для реального бизнеса. Смотрите, как мы решаем задачи клиентов.',
    'cases.viewAll': 'Смотреть все проекты',
    'cases.ecommerce.title': 'E-commerce платформа',
    'cases.ecommerce.client': 'Розничная сеть',
    'cases.ecommerce.description': 'Масштабируемый интернет-магазин с ML-рекомендациями.',
    'cases.ecommerce.result1': '+180% конверсия',
    'cases.ecommerce.result2': '3 месяца',
    'cases.ecommerce.result3': '50K+ пользователей',
    'cases.carRental.title': 'Платформа аренды автомобилей',
    'cases.carRental.client': 'Компания по аренде авто',
    'cases.carRental.description': 'Онлайн-платформа для аренды автомобилей с системой бронирования.',
    'cases.carRental.result1': '+120% бронирований',
    'cases.carRental.result2': '2 месяца',
    'cases.carRental.result3': '500+ автомобилей',
    'cases.realEstate.title': 'Сайт риелторского агентства',
    'cases.realEstate.client': 'Риелторское агентство',
    'cases.realEstate.description': 'Сайт для риелторского агентства с каталогом недвижимости.',
    'cases.realEstate.result1': '+200% заявок',
    'cases.realEstate.result2': '3 месяца',
    'cases.realEstate.result3': '1000+ объектов',
    'cases.transport.title': 'Управление транспортом',
    'cases.transport.client': 'Логистическая компания',
    'cases.transport.description': 'Система управления автопарком с отслеживанием в реальном времени.',
    'cases.transport.result1': '+40% эффективность',
    'cases.transport.result2': '3 месяца',
    'cases.transport.result3': '500+ автомобилей',
    'cases.automation.title': 'Автоматизация процессов',
    'cases.automation.client': 'Производство',
    'cases.automation.description': 'Система автоматизации рабочих процессов на производстве.',
    'cases.automation.result1': '-60% ручной работы',
    'cases.automation.result2': '5 месяцев',
    'cases.automation.result3': 'Работа 24/7',
    'cases.tron.title': 'Telegram Mini App Tron',
    'cases.tron.client': 'Игровая платформа',
    'cases.tron.description': 'Интерактивная игровая мини-апп для Telegram с увлекательным геймплеем.',
    'cases.tron.result1': '+300% вовлеченность',
    'cases.tron.result2': '1.5 месяца',
    'cases.tron.result3': '50K+ игроков',
    'cases.calculator.title': 'Telegram Mini App',
    'cases.calculator.client': 'Игровая платформа',
    'cases.calculator.description': 'Интерактивная игровая мини-апп для Telegram с увлекательным геймплеем.',

    // Case Modal UI
    'casemodal.projectDescription': 'Описание проекта',
    'casemodal.techStack': 'Технологии',
    'casemodal.results': 'Ключевые результаты',
    'casemodal.viewLive': 'Открыть',
    'casemodal.close': 'Закрыть',

    // Real cases
    'cases.supratrade.title': 'Supratrade — торговая платформа',
    'cases.supratrade.client': 'Supratrade',
    'cases.supratrade.description': 'Современная B2B-платформа для оптовой торговли с каталогом, личным кабинетом и админкой.',
    'cases.supratrade.long': 'Supratrade — это B2B-платформа для оптовой торговли, которую мы собрали «с нуля» как кастомное решение. Сайт объединил каталог товаров, процесс заказа и личный кабинет клиента в единую систему, что позволило компании быстрее подключать новых партнёров и управлять сделками.\n\nФронтенд построен на React + TypeScript с модульной архитектурой, ориентированной на скорость и удобный UX. Бэкенд на Node.js отвечает за авторизацию, каталог и обработку заказов, а PostgreSQL надёжно хранит товары, клиентов и транзакции. Отдельно сделали удобную админку, чтобы команда обновляла каталог без участия разработчиков.',
    'cases.supratrade.result1': '+150% целевых заявок',
    'cases.supratrade.result2': '3 месяца до запуска',
    'cases.supratrade.result3': '200+ B2B-партнёров',

    'cases.autoRent.title': 'AutoRent — сервис аренды авто',
    'cases.autoRent.client': 'Компания по аренде авто',
    'cases.autoRent.description': 'Онлайн-платформа аренды автомобилей с бронированием, оплатой и кабинетом водителя.',
    'cases.autoRent.long': 'AutoRent — полноценная платформа аренды автомобилей с бронированием, онлайн-оплатой и личным кабинетом. UX спроектирован вокруг скорости: пользователь фильтрует машины, выбирает даты, сразу видит цену и оплачивает в пару кликов.\n\nФронтенд — React с анимациями Framer Motion. API на Node.js, MongoDB хранит автопарк, бронирования и пользователей, оплата подключена через Stripe. В админке оператор добавляет машины, управляет тарифами, отслеживает бронирования в реальном времени и работает с клиентами.',
    'cases.autoRent.result1': '+120% онлайн-бронирований',
    'cases.autoRent.result2': '2 месяца до запуска',
    'cases.autoRent.result3': '500+ машин в парке',

    'cases.mosSeptik.title': 'Mos-Septik — септики и монтаж',
    'cases.mosSeptik.client': 'Mos-Septik',
    'cases.mosSeptik.description': 'Лендинг под SEO для компании по продаже и установке септиков.',
    'cases.mosSeptik.long': 'Mos-Septik — нишевый лендинг для компании по продаже и установке септиков. Главная задача — собирать заявки и занимать высокие позиции в поиске: мы сделали SEO-структуру, понятный каталог продукции, калькулятор, формы заявок и блоки доверия (кейсы, отзывы, сертификаты).\n\nСайт собран на React + Next.js, поэтому страницы отдаются серверно и хорошо индексируются. Tailwind обеспечивает стабильный дизайн и адаптив на любых устройствах. Все формы подключены к CRM — заявка сразу попадает к менеджеру.',
    'cases.mosSeptik.result1': 'Топ-10 в поиске',
    'cases.mosSeptik.result2': '1.5 месяца до запуска',
    'cases.mosSeptik.result3': '+210% заявок',

    'cases.blueberry.title': 'Blueberry — магазин ягодной фермы',
    'cases.blueberry.client': 'Blueberry Farm',
    'cases.blueberry.description': 'Интернет-магазин ягодной фермы с доставкой, оплатой и Telegram-ботом.',
    'cases.blueberry.long': 'Blueberry — интернет-магазин ягодной фермы: яркий сезонный каталог, оформление заказа, онлайн-оплата и интеграция с доставкой. Помимо магазина мы сделали Telegram-бота, который напоминает постоянным клиентам о новых поставках и подтверждает заказы.\n\nФронтенд на React даёт насыщенный и интерактивный UX. Node.js и PostgreSQL держат каталог, заказы и базу клиентов, оплата — через Stripe. Бот подключён к тому же бэкенду, поэтому заказы с сайта и из Telegram живут в одной системе.',
    'cases.blueberry.result1': '+180% онлайн-заказов',
    'cases.blueberry.result2': '2 месяца до запуска',
    'cases.blueberry.result3': '30K+ визитов в месяц',

    'cases.airGun.title': 'AirGun — магазин пневматики',
    'cases.airGun.client': 'AirGun Shop',
    'cases.airGun.description': 'Интернет-магазин пневматического оружия и аксессуаров.',
    'cases.airGun.long': 'AirGun — нишевый магазин пневматики, оптики и аксессуаров. Мы сделали упор на сильную карточку товара: характеристики, множество фото, отзывы, похожие товары и быстрая покупка «в один клик».\n\nСтек — React + TypeScript на клиенте и Node.js + PostgreSQL на сервере. Подключили онлайн-оплату для мгновенного чек-аута и связали админку с CRM менеджера — вся работа с заказами идёт в одном месте.',
    'cases.airGun.result1': '+140% конверсия в продажу',
    'cases.airGun.result2': '2.5 месяца до запуска',
    'cases.airGun.result3': '1500+ товаров',

    'cases.zapImport.title': 'ZapImport — импорт автозапчастей',
    'cases.zapImport.client': 'ZapImport',
    'cases.zapImport.description': 'Портал импорта автозапчастей с парсингом каталогов и REST API.',
    'cases.zapImport.long': 'ZapImport — B2B-портал импорта автозапчастей. Система агрегирует каталоги нескольких поставщиков, приводит данные к единому формату и даёт партнёрам единый поиск по VIN и артикулу. Самое сложное — собрать надёжный парсинг-пайплайн с актуальными ценами и остатками.\n\nФронтенд — React. Бэкенд на Node.js и PostgreSQL отвечает за парсинг, кэш и REST API, поэтому партнёры подключаются и через сайт, и напрямую через API.',
    'cases.zapImport.result1': '+300% объём заказов',
    'cases.zapImport.result2': '4 месяца до запуска',
    'cases.zapImport.result3': '50+ B2B-клиентов',

    // Testimonials Section
    'testimonials.badge': 'Отзывы',
    'testimonials.title': 'Что говорят',
    'testimonials.titleHighlight': 'наши клиенты',
    'testimonials.description': 'Реальные отзывы бизнесов, которым мы помогли вырасти в цифровом пространстве.',
    'testimonials.prev': 'Предыдущий отзыв',
    'testimonials.next': 'Следующий отзыв',
    'testimonials.t1': 'SnowTech сделали нам e-commerce платформу с нуля. Конверсия выросла на 180% в первый квартал — отличный результат, коммуникация всю дорогу была на высоте.',
    'testimonials.t2': 'Сильная команда — взяли нашу таргет-рекламу в TikTok и Instagram и за месяц снизили CPA вдвое. Отчётность понятная, дашборды прозрачные.',
    'testimonials.t3': 'Сделали сложный сайт для агентства недвижимости с продвинутыми фильтрами раньше срока. Поддержка после запуска — на уровне.',
    'testimonials.t4': 'Система управления автопарком наконец-то работает в реальном времени. Водители, операционка и руководство — все видят одну картину.',
    'testimonials.t5': 'Автоматизация, которую они настроили, убрала 60% ручных операций. ROI окупился за 4 месяца. Рекомендую без оговорок.',
    'testimonials.t6': 'Наш Telegram Mini App набрал 50K игроков за первые две недели. Геймплей нативный, UX затягивает, производительность идеальная.',

    // Contact Section
    'contact.badge': 'Контакты',
    'contact.title': 'Давайте обсудим ваш',
    'contact.titleHighlight': 'проект',
    'contact.description': 'Оставьте заявку, и мы свяжемся с вами в течение 24 часов для обсуждения деталей.',
    'contact.form.name': 'Ваше имя',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Телефон',
    'contact.form.message': 'Расскажите о вашем проекте',
    'contact.form.submit': 'Отправить заявку',
    'contact.form.success': 'Заявка отправлена!',
    'contact.form.successDesc': 'Мы свяжемся с вами в ближайшее время.',
    'contact.messenger': 'Или напишите в мессенджер:',

    // Footer
    'footer.description': 'Разрабатываем цифровые продукты, которые двигают бизнес. От сайтов до AI-решений.',
    'footer.services': 'Услуги',
    'footer.company': 'Компания',
    'footer.about': 'О нас',
    'footer.subscribe': 'Подпишитесь на обновления',
    'footer.subscribeBtn': 'Подписаться',
    'footer.rights': 'Все права защищены.',

    // Pricing Page
    'pricing.title': 'Цены',
    'pricing.subtitle': 'Прозрачные цены на все услуги. Выберите подходящий тариф или закажите индивидуальный расчёт.',
    'pricing.badge': 'Прозрачные цены',
    'pricing.from': 'от',
    'pricing.websites': 'Сайты',
    'pricing.additional': 'Дополнительные услуги',
    'pricing.landing': 'Лендинг',
    'pricing.landingDesc': 'Одностраничный сайт для рекламных кампаний',
    'pricing.corporate': 'Корпоративный сайт',
    'pricing.corporateDesc': 'Многостраничный сайт с админ-панелью',
    'pricing.store': 'Интернет-магазин',
    'pricing.storeDesc': 'Полноценный e-commerce с интеграцией оплаты',
    'pricing.platform': 'Веб-платформа',
    'pricing.platformDesc': 'Сложная система с кастомной логикой',
    'pricing.mobile': 'Мобильное приложение',
    'pricing.mobileDesc': 'iOS/Android приложение',
    'pricing.chatbot': 'Чат-бот',
    'pricing.chatbotDesc': 'Бот для мессенджеров',
    'pricing.ragbot': 'RAG-чат-бот',
    'pricing.ragbotDesc': 'AI-бот с базой знаний',
    'pricing.ml': 'ML-решение',
    'pricing.mlDesc': 'Кастомная ML-модель',
    'pricing.cv': 'Computer Vision',
    'pricing.cvDesc': 'Распознавание видео/изображений',
    'pricing.instagram': 'Таргет Instagram',
    'pricing.instagramDesc': 'Настройка рекламы + ведение',
    'pricing.tiktok': 'Реклама TikTok',
    'pricing.tiktokDesc': 'Настройка рекламной кампании',
    'pricing.support': 'Поддержка в месяц',
    'pricing.supportDesc': 'Техническая поддержка и обновления',
    'pricing.order': 'Заказать',
    'pricing.custom': 'Индивидуальный расчёт',
    'pricing.customDesc': 'Нужно что-то особенное? Рассчитаем индивидуальную стоимость для вашего проекта.',
    'pricing.customBtn': 'Получить расчёт',
    'pricing.flipHint': 'Наведите или коснитесь — итоговая цена обсуждается лично',
    'pricing.discussCta': 'Обсудить',

    // Blog Page
    'blog.title': 'Блог',
    'blog.subtitle': 'Полезные статьи о маркетинге, рекламе и продвижении бизнеса в Казахстане.',
    'blog.readMore': 'Читать далее',
    'blog.categories': 'Категории',
    'blog.all': 'Все',
    'blog.seo': 'SEO',
    'blog.smm': 'SMM',
    'blog.advertising': 'Реклама',
    'blog.automation': 'Автоматизация',

    // Cases Page
    'casesPage.title': 'Наши проекты',
    'casesPage.subtitle': 'Реальные кейсы с измеримыми результатами. Смотрите, как мы помогаем бизнесу расти.',
    'casesPage.empty': 'Кейсы скоро появятся',
    'casesPage.emptyDesc': 'Мы готовим подробные описания наших проектов. Следите за обновлениями!',

    // About Page
    'about.badge': 'О нас',
    'about.title': 'О SnowTEch',
    'about.subtitle': 'Мы команда IT-профессионалов, создающих цифровые продукты, которые двигают бизнес в Казахстане.',
    'about.demo.title': 'Интерактивные компоненты',
    'about.demo.rotate': 'Вращение',
    'about.demo.hover': 'Эффект наведения',
    'about.demo.color': 'Смена цвета',
    'about.values.title': 'Наши ценности',
    'about.values.innovation.title': 'Инновации',
    'about.values.innovation.description': 'Используем передовые технологии для создания современных решений.',
    'about.values.team.title': 'Команда',
    'about.values.team.description': 'Опытные профессионалы, работающие вместе для достижения ваших целей.',
    'about.values.quality.title': 'Качество',
    'about.values.quality.description': 'Создаём качественные продукты, соответствующие вашим ожиданиям.',
    'about.values.passion.title': 'Страсть',
    'about.values.passion.description': 'Мы любим то, что делаем, и это видно в нашей работе.',
    'about.cta.title': 'Готовы работать с нами?',
    'about.cta.description': 'Давайте обсудим ваш проект и создадим что-то удивительное вместе.',
    'about.cta.button': 'Связаться с нами',

    // Employee Pages
    'employee.iliyas.firstName': 'ИЛЬЯС',
    'employee.iliyas.lastName': 'КЕЛЕС',
    'employee.iliyas.role': 'FULL STACK DEVELOPER',
    'employee.iliyas.experience': 'ГОДА ОПЫТА',
    'employee.iliyas.technologies': 'ТЕХНОЛОГИЙ',
    'employee.iliyas.techStack': 'TECH STACK',
    'employee.iliyas.quote': '"С большой силой приходит большая ответственность"',
    'employee.iliyas.quoteAuthor': '- ПИТЕР ПАРКЕР',
    'employee.iliyas.nextEmployee': 'Следующий сотрудник SnowTEch',
    'employee.nurtore.firstName': 'НУРТОРЕ',
    'employee.nurtore.lastName': 'Келесов',
    'employee.nurtore.role': 'BACKEND DEVELOPER',
    'employee.nurtore.roleMobile': 'MOBILE DEVELOPER',
    'employee.nurtore.experience': 'ГОДА ОПЫТА',
    'employee.nurtore.technologies': 'ТЕХНОЛОГИЙ',
    'employee.nurtore.techStack': 'TECH STACK',
    'employee.nurtore.quote': '"Я создаю технологии, которые меняют мир"',
    'employee.nurtore.quoteAuthor': '- ТОНИ СТАРК',
    'employee.nurtore.previousEmployee': 'Предыдущий сотрудник SnowTEch',
  },
  kz: {
    // Navigation
    'nav.services': 'Қызметтер',
    'nav.whyUs': 'Неге біз',
    'nav.cases': 'Кейстер',
    'nav.pricing': 'Бағалар',
    'nav.blog': 'Блог',
    'nav.about': 'Біз туралы',
    'nav.contacts': 'Байланыс',
    'nav.discuss': 'Жобаны талқылау',
    'nav.back': 'Кері',

    // Hero Section
    'hero.badge': 'Бизнеске арналған IT-шешімдер',
    'hero.title1': 'Біз',
    'hero.title2': 'Цифрлық өнімдер',
    'hero.titleMobile': 'Қазақстанда кез келген күрделіліктегі сайттарды жасау',
    'hero.titleMobile.before': 'кез келген күрделіліктегі сайттарды жасау',
    'hero.titleMobile.highlight': 'Қазақстанда',
    'hero.title3': 'жасаймыз',
    'hero.description': 'Сайттар, мобильді қосымшалар, чат-боттар, AI-шешімдер және таргеттелген жарнама. Идеяларды жұмыс істейтін өнімдерге айналдырамыз.',
    'hero.cta1': 'Жобаны бастау',
    'hero.cta2': 'Біздің кейстер',
    'hero.stats.projects': 'Жобалар',
    'hero.stats.clients': 'Риза клиенттер',
    'hero.stats.years': 'Жыл тәжірибе',

    // Services Section
    'services.badge': 'Қызметтер',
    'services.title': 'Біз не',
    'services.titleHighlight': 'жасаймыз',
    'services.description': 'Цифрлық өнімдерді жасаудың толық циклі — идеядан іске қосу мен қолдауға дейін.',
    'services.shatterHint': 'Карталарды шайқаңыз — олардың бірі жеңілдік купонын жасырады',
    'services.productToastTitle': 'Заңгерлік ассистенттің жаңа демосы',
    'services.productToastDescription': 'Өнімді тексеріп көріңіз: негізгі заңдар бойынша жауап береді (ӘҚБтК және т.б.)',
    'services.coupon.congrats': 'Құттықтаймыз',
    'services.coupon.discountLabel': 'жеңілдік',
    'services.coupon.codeLabel': 'Купон коды',
    'services.coupon.cta': 'Хабарласу',
    'services.coupon.targetWeb': 'сайт әзірлеуге',
    'services.coupon.targetAll': 'барлық қызметтерге',
    'services.coupon.emptyTitle': 'Бос',
    'services.coupon.emptySubtitle': 'басқа картаны көріңіз',
    'services.coupon.waMessage':
      'Сәлеметсіз бе! SnowTech сайтында №{code} купонын ұттым ({discount} {target}). Жоба талқылағым келеді.',
    'services.web.title': 'Қазақстанда кез келген күрделіліктегі сайттарды жасау',
    'services.web.description': 'Лендингтер, корпоративтік сайттар, интернет-дүкендер, күрделі веб-платформалар. Заманауи технологиялар мен адаптивті дизайн.',
    'services.mobile.title': 'Мобильді қосымшалар',
    'services.mobile.description': 'iOS және Android үшін нативті және кросс-платформалық қосымшалар. MVP-ден enterprise шешімдерге дейін.',
    'services.chatbot.title': 'Чат-боттар',
    'services.chatbot.description': 'WhatsApp, Telegram және веб-сайттар үшін ақылды боттар. Клиенттермен қарым-қатынасты автоматтандыру.',
    'services.rag.title': 'RAG-чат-боттар',
    'services.rag.description': 'Білім базасы бар AI-боттар. Сіздің құжаттарыңыз бен деректеріңіз негізінде жауаптар.',
    'services.ml.title': 'Machine Learning',
    'services.ml.description': 'Болжамды аналитика, ұсыныс жүйелері, AI көмегімен процестерді автоматтандыру.',
    'services.cv.title': 'Computer Vision',
    'services.cv.description': 'Суреттер мен бейнелерді тану, объектілерді анықтау, сапаны бақылау жүйелері.',
    'services.ads.title': 'Таргеттелген жарнама',
    'services.ads.description': 'Instagram, TikTok, Facebook-та тиімді жарнама науқандары. Нақты таргетинг және ROI оңтайландыру.',
    'services.learnMore': 'Толығырақ',

    // Why Us Section
    'whyUs.badge': 'Артықшылықтар',
    'whyUs.title': 'Неге бізді',
    'whyUs.titleHighlight': 'таңдайды',
    'whyUs.description': 'Біз терең техникалық сараптаманы бизнес-міндеттерді түсінумен біріктіреміз.',
    'whyUs.expertise.title': 'Терең сараптама',
    'whyUs.expertise.description': 'Ірі жобаларда тәжірибесі бар мамандар командасы. Күрделі міндеттерді қалай шешуді білеміз.',
    'whyUs.approach.title': 'Жеке көзқарас',
    'whyUs.approach.description': 'Әр клиенттің ерекшеліктеріне терең енеміз. Шаблондық шешімдер жоқ.',
    'whyUs.deadlines.title': 'Мерзімдерді сақтау',
    'whyUs.deadlines.description': 'Мөлдір әзірлеу процесі және уақытылы тапсыру. Сіз әрқашан не болып жатқанын білесіз.',
    'whyUs.support.title': 'Қолдау және дамыту',
    'whyUs.support.description': 'Жобаларды тастамаймыз. Техникалық қолдау және үнемі жетілдіру.',
    'whyUs.tech.title': 'Технологиялық стек',
    'whyUs.tech.description': 'Сенімді және масштабталатын шешімдер үшін заманауи технологияларды қолданамыз.',

    // Cases Section
    'cases.badge': 'Кейстер',
    'cases.title': 'Біз мақтанатын',
    'cases.titleHighlight': 'жобалар',
    'cases.description': 'Нақты бизнес үшін нақты нәтижелер. Клиенттердің міндеттерін қалай шешетінімізді қараңыз.',
    'cases.viewAll': 'Барлық жобаларды көру',
    'cases.ecommerce.title': 'E-commerce платформа',
    'cases.ecommerce.client': 'Бөлшек сауда желісі',
    'cases.ecommerce.description': 'ML-ұсыныстары бар масштабталатын интернет-дүкен.',
    'cases.ecommerce.result1': '+180% конверсия',
    'cases.ecommerce.result2': '3 ай',
    'cases.ecommerce.result3': '50K+ пайдаланушы',
    'cases.carRental.title': 'Көлік жалдау платформасы',
    'cases.carRental.client': 'Көлік жалдау компаниясы',
    'cases.carRental.description': 'Брондау жүйесі бар көлік жалдауға арналған онлайн-платформа.',
    'cases.carRental.result1': '+120% брондау',
    'cases.carRental.result2': '2 ай',
    'cases.carRental.result3': '500+ көлік',
    'cases.realEstate.title': 'Жылжымайтын мүлік агенттігі сайты',
    'cases.realEstate.client': 'Жылжымайтын мүлік агенттігі',
    'cases.realEstate.description': 'Жылжымайтын мүлік каталогы бар агенттік сайты.',
    'cases.realEstate.result1': '+200% сұрау',
    'cases.realEstate.result2': '3 ай',
    'cases.realEstate.result3': '1000+ объект',
    'cases.transport.title': 'Көлікті басқару',
    'cases.transport.client': 'Логистикалық компания',
    'cases.transport.description': 'Нақты уақытта бақылаумен автопарк басқару жүйесі.',
    'cases.transport.result1': '+40% тиімділік',
    'cases.transport.result2': '3 ай',
    'cases.transport.result3': '500+ көлік',
    'cases.automation.title': 'Процестерді автоматтандыру',
    'cases.automation.client': 'Өндіріс',
    'cases.automation.description': 'Өндірістік процестерді автоматтандыру жүйесі.',
    'cases.automation.result1': '-60% қол жұмысы',
    'cases.automation.result2': '5 ай',
    'cases.automation.result3': '24/7 жұмыс',
    'cases.tron.title': 'Telegram Mini App Tron',
    'cases.tron.client': 'Ойын платформасы',
    'cases.tron.description': 'Қызықты ойын процесімен Telegram үшін интерактивті ойын мини-апп.',
    'cases.tron.result1': '+300% қатысу',
    'cases.tron.result2': '1.5 ай',
    'cases.tron.result3': '50K+ ойыншы',
    'cases.calculator.title': 'Telegram Mini App',
    'cases.calculator.client': 'Ойын платформасы',
    'cases.calculator.description': 'Қызықты ойын процесімен Telegram үшін интерактивті ойын мини-апп.',

    // Case Modal UI
    'casemodal.projectDescription': 'Жоба сипаттамасы',
    'casemodal.techStack': 'Технологиялар',
    'casemodal.results': 'Негізгі нәтижелер',
    'casemodal.viewLive': 'Ашу',
    'casemodal.close': 'Жабу',

    // Real cases
    'cases.supratrade.title': 'Supratrade — сауда платформасы',
    'cases.supratrade.client': 'Supratrade',
    'cases.supratrade.description': 'Каталогы, жеке кабинеті және басқару панелі бар заманауи B2B сауда платформасы.',
    'cases.supratrade.long': 'Supratrade — біз нөлден құрастырған B2B сауда платформасы. Сайт тауар каталогын, тапсырыс процесін және клиенттің жеке кабинетін біртұтас жүйеге біріктірді. Осының арқасында компания жаңа серіктестерді тезірек қосып, мәмілелерді оңай басқарады.\n\nФронтенд React + TypeScript негізінде модульді архитектурамен жасалған. Бэкенд Node.js авторизация, каталог және тапсырыстармен жұмыс істейді, ал PostgreSQL өнімдер мен клиенттерді сенімді сақтайды. Әкімшілік панель каталогты әзірлеушілерсіз жаңартуға мүмкіндік береді.',
    'cases.supratrade.result1': '+150% мақсатты сұраныс',
    'cases.supratrade.result2': '3 айда іске қосу',
    'cases.supratrade.result3': '200+ B2B серіктес',

    'cases.autoRent.title': 'AutoRent — көлік жалдау сервисі',
    'cases.autoRent.client': 'Көлік жалдау компаниясы',
    'cases.autoRent.description': 'Брондау, онлайн-төлем және жүргізуші кабинеті бар көлік жалдау платформасы.',
    'cases.autoRent.long': 'AutoRent — брондау, онлайн-төлем және жеке кабинеті бар толыққанды көлік жалдау платформасы. UX жылдамдыққа құрылған: пайдаланушы көліктерді сүзеді, күнді таңдайды, бағаны дереу көріп, бірнеше рет басумен төлейді.\n\nФронтенд — Framer Motion анимацияларымен React. API Node.js-та, MongoDB автопаркті, брондауларды және пайдаланушыларды сақтайды, төлемдер Stripe арқылы. Әкімшілік панель көліктерді қосуға, тарифтерді басқаруға және брондауларды бақылауға мүмкіндік береді.',
    'cases.autoRent.result1': '+120% онлайн-брондау',
    'cases.autoRent.result2': '2 айда іске қосу',
    'cases.autoRent.result3': '500+ көлік',

    'cases.mosSeptik.title': 'Mos-Septik — септиктер және монтаж',
    'cases.mosSeptik.client': 'Mos-Septik',
    'cases.mosSeptik.description': 'Септик сату және орнату компаниясы үшін SEO-ға бағытталған лендинг.',
    'cases.mosSeptik.long': 'Mos-Septik — септик сату және орнату компаниясына арналған нишалық лендинг. Негізгі мақсат — өтінімдерді жинау және іздеуде жоғары орын алу: біз SEO құрылымын, каталогты, калькуляторды, өтінім формаларын және сенім блоктарын жасадық.\n\nСайт React + Next.js негізінде жиналған, сондықтан беттер серверлі рендерленіп, жақсы индекстеледі. Tailwind кез келген құрылғыға арналған біркелкі дизайн мен адаптивтілікті қамтамасыз етеді. Барлық формалар CRM-ге қосылған.',
    'cases.mosSeptik.result1': 'Іздеуде Топ-10',
    'cases.mosSeptik.result2': '1.5 айда іске қосу',
    'cases.mosSeptik.result3': '+210% өтінім',

    'cases.blueberry.title': 'Blueberry — жидек фермасының дүкені',
    'cases.blueberry.client': 'Blueberry Farm',
    'cases.blueberry.description': 'Жеткізу, төлем және Telegram-боты бар жидек фермасының интернет-дүкені.',
    'cases.blueberry.long': 'Blueberry — жидек фермасының интернет-дүкені: жарқын маусымдық каталог, тапсырысты ресімдеу, онлайн-төлем және жеткізу интеграциясы. Дүкеннен бөлек біз тұрақты клиенттерге жаңа түсімдер туралы еске салатын Telegram-ботты жасадық.\n\nReact-тегі фронтенд бай интерактивті UX береді. Node.js пен PostgreSQL каталог пен клиенттерді ұстайды, төлем — Stripe арқылы. Бот сол бэкендке қосылған, сондықтан сайттан және Telegram-нан келген тапсырыстар бір жүйеде.',
    'cases.blueberry.result1': '+180% онлайн-тапсырыс',
    'cases.blueberry.result2': '2 айда іске қосу',
    'cases.blueberry.result3': 'Айына 30K+ кіру',

    'cases.airGun.title': 'AirGun — пневматика дүкені',
    'cases.airGun.client': 'AirGun Shop',
    'cases.airGun.description': 'Пневматика және аксессуарларға арналған интернет-дүкен.',
    'cases.airGun.long': 'AirGun — пневматика, оптика және аксессуарлардың нишалық дүкені. Біз күшті өнім карточкасына назар аудардық: сипаттамалар, көптеген фото, пікірлер, ұқсас өнімдер және «бір рет басумен сатып алу».\n\nСтек — клиентте React + TypeScript және серверде Node.js + PostgreSQL. Жедел төлем үшін онлайн-төлемді қостық және менеджер CRM-ін әкімшілік панельмен байланыстырдық.',
    'cases.airGun.result1': '+140% сатуға конверсия',
    'cases.airGun.result2': '2.5 айда іске қосу',
    'cases.airGun.result3': '1500+ тауар',

    'cases.zapImport.title': 'ZapImport — қосалқы бөлшектер импорты',
    'cases.zapImport.client': 'ZapImport',
    'cases.zapImport.description': 'Каталог парсингі және REST API бар автобөлшектер импорты порталы.',
    'cases.zapImport.long': 'ZapImport — автокөлік қосалқы бөлшектерінің B2B порталы. Жүйе бірнеше жеткізушінің каталогтарын жинап, деректерді бір форматқа келтіреді және серіктестерге VIN мен артикул бойынша біртұтас іздеу береді. Ең күрделісі — өзекті бағалар мен қалдықтармен сенімді парсинг жасау.\n\nФронтенд — React. Node.js пен PostgreSQL негізіндегі бэкенд парсинг пен REST API-ды ұстайды, сондықтан серіктестер сайт арқылы да, API арқылы да қосылады.',
    'cases.zapImport.result1': '+300% тапсырыс көлемі',
    'cases.zapImport.result2': '4 айда іске қосу',
    'cases.zapImport.result3': '50+ B2B клиент',

    // Testimonials Section
    'testimonials.badge': 'Пікірлер',
    'testimonials.title': 'Клиенттеріміз',
    'testimonials.titleHighlight': 'не айтады',
    'testimonials.description': 'Цифрлық кеңістікте өсуге көмектескен бизнестердің нақты пікірлері.',
    'testimonials.prev': 'Алдыңғы пікір',
    'testimonials.next': 'Келесі пікір',
    'testimonials.t1': 'SnowTech бізге e-commerce платформасын нөлден жасап берді. Бірінші тоқсанда конверсия 180%-ға өсті — тамаша нәтиже, байланыс та жоғары деңгейде болды.',
    'testimonials.t2': 'Күшті команда — TikTok пен Instagram-дағы таргет-жарнамамызды алды да, бір айда CPA-ны екі есе азайтты. Есептер түсінікті, дашбордтар мөлдір.',
    'testimonials.t3': 'Жылжымайтын мүлік агенттігіне күрделі фильтрлері бар сайтты мерзімінен бұрын жасап берді. Іске қосқаннан кейінгі қолдау — жоғары сапалы.',
    'testimonials.t4': 'Автопаркті басқару жүйеміз ақыры нақты уақытта жұмыс істейді. Жүргізушілер, операциялық команда және басшылық бір сурет көреді.',
    'testimonials.t5': 'Олар баптаған автоматтандыру қолмен жасалатын жұмыстың 60%-ын алып тастады. ROI 4 айда өтелді. Ешбір ескертпесіз ұсынамын.',
    'testimonials.t6': 'Telegram Mini App-қа алғашқы екі аптада 50K ойыншы жиналды. Геймплей нативті, UX қызықтырады, өнімділік мінсіз.',

    // Contact Section
    'contact.badge': 'Байланыс',
    'contact.title': 'Сіздің жобаңызды',
    'contact.titleHighlight': 'талқылайық',
    'contact.description': 'Өтініш қалдырыңыз, біз 24 сағат ішінде мәліметтерді талқылау үшін хабарласамыз.',
    'contact.form.name': 'Сіздің атыңыз',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Телефон',
    'contact.form.message': 'Жобаңыз туралы айтыңыз',
    'contact.form.submit': 'Өтініш жіберу',
    'contact.form.success': 'Өтініш жіберілді!',
    'contact.form.successDesc': 'Біз жақын арада хабарласамыз.',
    'contact.messenger': 'Немесе мессенджерге жазыңыз:',

    // Footer
    'footer.description': 'Бизнесті алға жылжытатын цифрлық өнімдер әзірлейміз. Сайттардан AI-шешімдерге дейін.',
    'footer.services': 'Қызметтер',
    'footer.company': 'Компания',
    'footer.about': 'Біз туралы',
    'footer.subscribe': 'Жаңалықтарға жазылыңыз',
    'footer.subscribeBtn': 'Жазылу',
    'footer.rights': 'Барлық құқықтар қорғалған.',

    // Pricing Page
    'pricing.title': 'Бағалар',
    'pricing.subtitle': 'Барлық қызметтерге мөлдір бағалар. Қолайлы тарифті таңдаңыз немесе жеке есептеуге тапсырыс беріңіз.',
    'pricing.badge': 'Мөлдір бағалар',
    'pricing.from': 'бастап',
    'pricing.websites': 'Сайттар',
    'pricing.additional': 'Қосымша қызметтер',
    'pricing.landing': 'Лендинг',
    'pricing.landingDesc': 'Жарнамалық науқандарға арналған бір беттік сайт',
    'pricing.corporate': 'Корпоративтік сайт',
    'pricing.corporateDesc': 'Админ панелі бар көп беттік сайт',
    'pricing.store': 'Интернет-дүкен',
    'pricing.storeDesc': 'Төлем интеграциясы бар толыққанды e-commerce',
    'pricing.platform': 'Веб-платформа',
    'pricing.platformDesc': 'Кастомдық логикасы бар күрделі жүйе',
    'pricing.mobile': 'Мобильді қосымша',
    'pricing.mobileDesc': 'iOS/Android қосымшасы',
    'pricing.chatbot': 'Чат-бот',
    'pricing.chatbotDesc': 'Мессенджерлерге арналған бот',
    'pricing.ragbot': 'RAG-чат-бот',
    'pricing.ragbotDesc': 'Білім базасы бар AI-бот',
    'pricing.ml': 'ML-шешім',
    'pricing.mlDesc': 'Кастомдық ML-модель',
    'pricing.cv': 'Computer Vision',
    'pricing.cvDesc': 'Бейне/сурет тану',
    'pricing.instagram': 'Instagram таргет',
    'pricing.instagramDesc': 'Жарнама баптау + жүргізу',
    'pricing.tiktok': 'TikTok жарнамасы',
    'pricing.tiktokDesc': 'Жарнама науқанын баптау',
    'pricing.support': 'Айлық қолдау',
    'pricing.supportDesc': 'Техникалық қолдау және жаңартулар',
    'pricing.order': 'Тапсырыс беру',
    'pricing.custom': 'Жеке есептеу',
    'pricing.customDesc': 'Ерекше нәрсе керек пе? Жобаңыз үшін жеке құнын есептейміз.',
    'pricing.customBtn': 'Есептеу алу',
    'pricing.flipHint': 'Тигізіңіз — соңғы баға жеке талқыланады',
    'pricing.discussCta': 'Талқылау',

    // Blog Page
    'blog.title': 'Блог',
    'blog.subtitle': 'Қазақстанда маркетинг, жарнама және бизнесті жылжыту туралы пайдалы мақалалар.',
    'blog.readMore': 'Толығырақ оқу',
    'blog.categories': 'Санаттар',
    'blog.all': 'Барлығы',
    'blog.seo': 'SEO',
    'blog.smm': 'SMM',
    'blog.advertising': 'Жарнама',
    'blog.automation': 'Автоматтандыру',

    // Cases Page
    'casesPage.title': 'Біздің жобалар',
    'casesPage.subtitle': 'Өлшенетін нәтижелері бар нақты кейстер. Бизнестің өсуіне қалай көмектесетінімізді қараңыз.',
    'casesPage.empty': 'Кейстер жақында қосылады',
    'casesPage.emptyDesc': 'Жобаларымыздың толық сипаттамаларын дайындап жатырмыз. Жаңалықтарды қадағалаңыз!',

    // About Page
    'about.badge': 'Біз туралы',
    'about.title': 'SnowTEch туралы',
    'about.subtitle': 'Біз Қазақстанда бизнесті алға жылжытатын цифрлық өнімдер жасайтын IT мамандары командасымыз.',
    'about.demo.title': 'Интерактивті компоненттер',
    'about.demo.rotate': 'Айналу',
    'about.demo.hover': 'Үстінен өту эффектісі',
    'about.demo.color': 'Түс өзгерту',
    'about.values.title': 'Біздің құндылықтарымыз',
    'about.values.innovation.title': 'Инновация',
    'about.values.innovation.description': 'Заманауи шешімдер жасау үшін озық технологияларды қолданамыз.',
    'about.values.team.title': 'Команда',
    'about.values.team.description': 'Сіздің мақсаттарыңызға қол жеткізу үшін бірге жұмыс істейтін тәжірибелі мамандар.',
    'about.values.quality.title': 'Сапа',
    'about.values.quality.description': 'Сіздің күтулеріңізге сәйкес келетін сапалы өнімдер жасаймыз.',
    'about.values.passion.title': 'Құмарлық',
    'about.values.passion.description': 'Біз не істейтінімізді жақсы көреміз және бұл біздің жұмысымызда көрінеді.',
    'about.cta.title': 'Бізбен жұмыс істеуге дайынсыз ба?',
    'about.cta.description': 'Жобаңызды талқылап, бірге керемет нәрсе жасайық.',
    'about.cta.button': 'Байланысу',

    // Employee Pages
    'employee.iliyas.firstName': 'ИЛЬЯС',
    'employee.iliyas.lastName': 'КЕЛЕС',
    'employee.iliyas.role': 'FULL STACK DEVELOPER',
    'employee.iliyas.experience': 'ТӘЖІРИБЕ ЖЫЛДАРЫ',
    'employee.iliyas.technologies': 'ТЕХНОЛОГИЯЛАР',
    'employee.iliyas.techStack': 'TECH STACK',
    'employee.iliyas.quote': '"Үлкен күш үлкен жауапкершілікпен келеді"',
    'employee.iliyas.quoteAuthor': '- ПИТЕР ПАРКЕР',
    'employee.iliyas.nextEmployee': 'Келесі SnowTEch қызметкері',
    'employee.nurtore.firstName': 'НУРТОРЕ',
    'employee.nurtore.lastName': 'Келесов',
    'employee.nurtore.role': 'BACKEND DEVELOPER',
    'employee.nurtore.roleMobile': 'MOBILE DEVELOPER',
    'employee.nurtore.experience': 'ТӘЖІРИБЕ ЖЫЛДАРЫ',
    'employee.nurtore.technologies': 'ТЕХНОЛОГИЯЛАР',
    'employee.nurtore.techStack': 'TECH STACK',
    'employee.nurtore.quote': '"Әлемді өзгертетін технологиялар жасаймын"',
    'employee.nurtore.quoteAuthor': '- ТОНИ СТАРК',
    'employee.nurtore.previousEmployee': 'Алдыңғы SnowTEch қызметкері',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'kz' ? 'kk' : language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
